// Package builder implements the agent build and upgrade pipeline.
package builder

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/airlockrun/airlock/scaffold"
)

// Per-agent repo layout:
//
//	<basePath>/                     ← AgentReposPath
//	├── <agentID-1>/                ← per-agent repo working tree
//	│   ├── .git/
//	│   ├── main.go
//	│   ├── go.mod
//	│   ├── ...
//	├── <agentID-2>/
//	│   └── ...
//
// AgentRepoPath returns the working-tree path for a single agent's repo.
func AgentRepoPath(basePath, agentID string) string {
	return filepath.Join(basePath, agentID)
}

// InitAgentRepo initializes a per-agent git repo at <basePath>/<agentID>/
// if it doesn't already exist. Idempotent.
//
// Sets receive.denyCurrentBranch=updateInstead so the per-upgrade clone
// can push back into the checked-out branch of this repo. The initial
// commit (with .gitignore) gives the repo a HEAD so subsequent
// `git checkout main` works without complaints.
func InitAgentRepo(basePath, agentID string) error {
	path := AgentRepoPath(basePath, agentID)
	if _, err := os.Stat(filepath.Join(path, ".git")); err == nil {
		return nil // already initialized
	}

	if err := os.MkdirAll(path, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", path, err)
	}

	if err := git(path, "init", "-b", "main"); err != nil {
		return fmt.Errorf("git init: %w", err)
	}

	if err := git(path, "config", "user.email", "airlock@localhost"); err != nil {
		return fmt.Errorf("git config email: %w", err)
	}
	if err := git(path, "config", "user.name", "Airlock"); err != nil {
		return fmt.Errorf("git config name: %w", err)
	}

	// Allow pushes from the per-upgrade clone back into this repo's
	// currently-checked-out branch (the upgrade branch).
	if err := git(path, "config", "receive.denyCurrentBranch", "updateInstead"); err != nil {
		return fmt.Errorf("git config receive: %w", err)
	}

	// DIAGNOSTICS.md and Dockerfile are generated by Airlock before a
	// build/upgrade and should not be committed to the agent source tree.
	if err := os.WriteFile(filepath.Join(path, ".gitignore"), []byte("DIAGNOSTICS.md\nDockerfile\n"), 0o644); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}
	if err := git(path, "add", ".gitignore"); err != nil {
		return fmt.Errorf("git add .gitignore: %w", err)
	}
	if err := git(path, "commit", "-m", "init"); err != nil {
		return fmt.Errorf("git initial commit: %w", err)
	}

	return nil
}

// CommitScaffold creates branch build/init in the agent's repo,
// materializes scaffold files at the repo root, and commits. Returns the
// commit hash. Safe to call on retry — deletes a stale branch first.
func CommitScaffold(repoPath string, data scaffold.ScaffoldData) (string, error) {
	const branch = "build/init"

	// Clean up stale branch from a previous failed build attempt.
	// Must switch away from it first — can't delete the checked-out branch.
	_ = git(repoPath, "checkout", "main")
	_ = git(repoPath, "branch", "-D", branch)

	if err := git(repoPath, "checkout", "-b", branch); err != nil {
		return "", fmt.Errorf("git checkout -b %s: %w", branch, err)
	}

	// Materialize scaffold at the repo root (no agents/<id>/ nesting).
	if err := scaffold.Materialize(repoPath, data); err != nil {
		return "", fmt.Errorf("materialize scaffold: %w", err)
	}

	if err := git(repoPath, "add", "-A"); err != nil {
		return "", fmt.Errorf("git add: %w", err)
	}

	// Retry safety: a previous build may have already merged the same
	// scaffold to main. Since we just re-created the build branch from
	// main, the materialized files match what's already committed and
	// there's nothing to stage. Treat that as success — MergeBranch is a
	// no-op when the branch is already merged.
	status, err := gitOutput(repoPath, "status", "--porcelain")
	if err != nil {
		return "", fmt.Errorf("git status: %w", err)
	}
	if status == "" {
		hash, err := gitOutput(repoPath, "rev-parse", "HEAD")
		if err != nil {
			return "", fmt.Errorf("git rev-parse: %w", err)
		}
		return hash, nil
	}

	if err := git(repoPath, "commit", "-m", "scaffold"); err != nil {
		return "", fmt.Errorf("git commit: %w", err)
	}

	hash, err := gitOutput(repoPath, "rev-parse", "HEAD")
	if err != nil {
		return "", fmt.Errorf("git rev-parse: %w", err)
	}
	return hash, nil
}

// CreateBranch creates a new branch from main in repoPath.
func CreateBranch(repoPath, branch string) error {
	if err := git(repoPath, "checkout", "main"); err != nil {
		if err2 := git(repoPath, "checkout", "master"); err2 != nil {
			return fmt.Errorf("git checkout main: %w", err)
		}
	}
	_ = git(repoPath, "branch", "-D", branch)
	if err := git(repoPath, "checkout", "-b", branch); err != nil {
		return fmt.Errorf("git checkout -b %s: %w", branch, err)
	}
	return nil
}

// CreateUpgradeBranch creates branch upgrade/{runID} in the agent's repo
// off main. Uses `-B` (create-or-reset) so retries don't fail on a
// leftover branch from a prior failed attempt — Fix-this-error reuses
// the failed run's id as the branch suffix, and successful upgrades
// currently never delete the branch after merging, so collisions are
// easy to hit. Whatever was on the old branch was from a failed run and
// not worth keeping.
func CreateUpgradeBranch(repoPath, runID string) error {
	branch := upgradeBranchName(runID)

	if err := git(repoPath, "checkout", "main"); err != nil {
		if err2 := git(repoPath, "checkout", "master"); err2 != nil {
			return fmt.Errorf("git checkout main: %w", err)
		}
	}
	if err := git(repoPath, "checkout", "-B", branch); err != nil {
		return fmt.Errorf("git checkout -B %s: %w", branch, err)
	}
	return nil
}

// UpgradeBranchName returns the branch name an upgrade run lives on
// inside the agent's repo. Exposed so callers can hand the same name to
// CloneAgentRepo and MergeBranch.
func UpgradeBranchName(runID string) string { return upgradeBranchName(runID) }

func upgradeBranchName(runID string) string { return "upgrade/" + runID }

// CloneAgentRepo clones the agent's repo into targetDir on the given
// branch. The full source tree lives at the targetDir root (no
// agents/<id>/ subdir) — the per-agent repo's scaffold and codegen
// commits put files at the repo root.
//
// Replaces the pre-multirepo SparseCheckout, which had to narrow a
// monorepo clone down to one agent's subtree.
func CloneAgentRepo(repoPath, branch, targetDir string) error {
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", targetDir, err)
	}

	if err := runGit(targetDir, "clone", "--filter=blob:none", "--branch", branch, repoPath, "."); err != nil {
		return fmt.Errorf("git clone: %w", err)
	}

	// Mark the workspace as safe for both host path and container mount path.
	if err := git(targetDir, "config", "safe.directory", targetDir); err != nil {
		return fmt.Errorf("git config safe.directory: %w", err)
	}
	// The toolserver container mounts this dir at /workspace.
	_ = git(targetDir, "config", "--add", "safe.directory", "/workspace")

	if err := git(targetDir, "config", "user.email", "airlock@localhost"); err != nil {
		return fmt.Errorf("git config email: %w", err)
	}
	if err := git(targetDir, "config", "user.name", "Airlock"); err != nil {
		return fmt.Errorf("git config name: %w", err)
	}

	return nil
}

// CommitAndPush commits all changes on the current branch in workDir,
// pushes to origin. Returns commit hash. No-op + current HEAD when the
// tree is clean.
func CommitAndPush(workDir, message string) (string, error) {
	if err := git(workDir, "add", "-A"); err != nil {
		return "", fmt.Errorf("git add: %w", err)
	}

	status, err := gitOutput(workDir, "status", "--porcelain")
	if err != nil {
		return "", fmt.Errorf("git status: %w", err)
	}
	if status == "" {
		hash, err := gitOutput(workDir, "rev-parse", "HEAD")
		if err != nil {
			return "", fmt.Errorf("git rev-parse: %w", err)
		}
		return hash, nil
	}

	if err := git(workDir, "commit", "-m", message); err != nil {
		return "", fmt.Errorf("git commit: %w", err)
	}

	hash, err := gitOutput(workDir, "rev-parse", "HEAD")
	if err != nil {
		return "", fmt.Errorf("git rev-parse: %w", err)
	}

	if err := git(workDir, "push", "origin", "HEAD"); err != nil {
		return "", fmt.Errorf("git push: %w", err)
	}

	return hash, nil
}

// MergeBranch fast-forward merges branch into main, rebasing the branch
// onto current main first if a parallel commit advanced main while this
// branch's work was running. With per-agent repos each agent's history
// is isolated, so the rebase trivially fast-forwards in the common case;
// the fallback path handles the rare case of a manual commit landing on
// main (e.g. an operator hot-fix) in parallel with a build.
func MergeBranch(repoPath, branch string) error {
	mainBranch := "main"
	if err := git(repoPath, "checkout", "main"); err != nil {
		if err2 := git(repoPath, "checkout", "master"); err2 != nil {
			return fmt.Errorf("git checkout main: %w", err)
		}
		mainBranch = "master"
	}

	if err := git(repoPath, "merge", "--ff-only", branch); err == nil {
		return nil
	}

	if err := git(repoPath, "rebase", mainBranch, branch); err != nil {
		_ = git(repoPath, "rebase", "--abort")
		_ = git(repoPath, "checkout", mainBranch)
		return fmt.Errorf("git rebase %s onto %s: %w", branch, mainBranch, err)
	}
	if err := git(repoPath, "checkout", mainBranch); err != nil {
		return fmt.Errorf("git checkout %s after rebase: %w", mainBranch, err)
	}
	if err := git(repoPath, "merge", "--ff-only", branch); err != nil {
		return fmt.Errorf("git merge --ff-only %s after rebase: %w", branch, err)
	}
	return nil
}

// RemoveAgentRepo deletes the per-agent repo directory entirely.
// Idempotent — missing dir is not an error.
func RemoveAgentRepo(basePath, agentID string) error {
	path := AgentRepoPath(basePath, agentID)
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
	if err := os.RemoveAll(path); err != nil {
		return fmt.Errorf("remove agent repo %s: %w", path, err)
	}
	return nil
}

// git runs a git command in the given directory.
func git(dir string, args ...string) error {
	return runGit(dir, args...)
}

// runGit runs a git command in the given directory.
func runGit(dir string, args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(gitCleanEnv(), "GIT_TERMINAL_PROMPT=0")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// gitOutput runs a git command and returns its stdout.
func gitOutput(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(gitCleanEnv(), "GIT_TERMINAL_PROMPT=0")
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return "", fmt.Errorf("%s: %s", err, strings.TrimSpace(string(ee.Stderr)))
		}
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// gitCleanEnv returns os.Environ() with git-context vars stripped. These
// leak in when builder tests run inside a pre-commit hook (git sets
// GIT_INDEX_FILE and friends pointing at the parent repo's in-flight
// index, which breaks any git subprocess that tries to use its own repo).
func gitCleanEnv() []string {
	env := os.Environ()
	out := env[:0]
	for _, kv := range env {
		eq := strings.IndexByte(kv, '=')
		if eq < 0 {
			out = append(out, kv)
			continue
		}
		k := kv[:eq]
		if strings.HasPrefix(k, "GIT_") {
			continue
		}
		out = append(out, kv)
	}
	return out
}
