// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_runtime.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAppRun = `-- name: CompleteAppRun :execrows
UPDATE runs r SET
    status = $1,
    error_message = $2,
    error_kind = $3,
    actions = $4,
    stdout_log = $5,
    panic_trace = $6,
    finished_at = now(),
    duration_ms = (EXTRACT(EPOCH FROM (now() - r.started_at)) * 1000)::integer
FROM agents app, execution_origins origin
WHERE r.id = $7 AND r.agent_id = $8
  AND app.id = r.agent_id AND app.agent_token_version = $9
  AND app.status IN ('active', 'building')
  AND origin.id = r.origin_id AND origin.agent_id = r.agent_id AND origin.actor <> 'unknown'
  AND r.status = 'running' AND r.runtime_owner_token IS NULL
  AND r.execution_kind <> 'prompt'
  AND (origin.actor <> 'app' OR r.execution_kind = 'job' OR origin.runtime_generation = $9)
  AND $1::text IN ('success', 'error', 'timeout', 'cancelled', 'tool_errors')
  AND (
    (r.execution_kind <> 'job' AND r.trigger_type <> 'job' AND $10::uuid IS NULL)
    OR EXISTS (
      SELECT 1 FROM agent_jobs job JOIN agent_job_attempts attempt ON attempt.job_id = job.id
      WHERE job.id = $10 AND job.agent_id = r.agent_id
        AND job.status = 'running' AND job.cancel_requested_at IS NULL
        AND attempt.run_id = r.id AND attempt.attempt_number = $11
        AND attempt.lease_token = $12 AND attempt.runtime_generation = $9
        AND attempt.status = 'running' AND attempt.lease_expires_at > clock_timestamp()
    )
  )
`

type CompleteAppRunParams struct {
	Status        string      `json:"status"`
	ErrorMessage  string      `json:"error_message"`
	ErrorKind     string      `json:"error_kind"`
	Actions       []byte      `json:"actions"`
	StdoutLog     string      `json:"stdout_log"`
	PanicTrace    string      `json:"panic_trace"`
	RunID         pgtype.UUID `json:"run_id"`
	AgentID       pgtype.UUID `json:"agent_id"`
	TokenVersion  int64       `json:"token_version"`
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

// Completion is an update of admitted work, fenced by the current app credential
// and, for job deliveries, the exact live invocation attempt.
func (q *Queries) CompleteAppRun(ctx context.Context, arg CompleteAppRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAppRun,
		arg.Status,
		arg.ErrorMessage,
		arg.ErrorKind,
		arg.Actions,
		arg.StdoutLog,
		arg.PanicTrace,
		arg.RunID,
		arg.AgentID,
		arg.TokenVersion,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
