// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: async_origins.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsyncChatOrigin = `-- name: CreateAsyncChatOrigin :one
INSERT INTO async_chat_origins (agent_id, user_id, source_run_id, system_run_id)
VALUES ($1, $2, $3, $4) RETURNING id, agent_id, user_id, source_run_id, system_run_id
`

type CreateAsyncChatOriginParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	UserID      pgtype.UUID `json:"user_id"`
	SourceRunID pgtype.UUID `json:"source_run_id"`
	SystemRunID pgtype.UUID `json:"system_run_id"`
}

func (q *Queries) CreateAsyncChatOrigin(ctx context.Context, arg CreateAsyncChatOriginParams) (AsyncChatOrigin, error) {
	row := q.db.QueryRow(ctx, createAsyncChatOrigin,
		arg.AgentID,
		arg.UserID,
		arg.SourceRunID,
		arg.SystemRunID,
	)
	var i AsyncChatOrigin
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.SourceRunID,
		&i.SystemRunID,
	)
	return i, err
}

const getAsyncChatOrigin = `-- name: GetAsyncChatOrigin :one
SELECT o.id, o.agent_id, o.user_id, o.source_run_id, o.system_run_id, r.caller_conversation_id AS conversation_id, s.conversation_id AS system_conversation_id
FROM async_chat_origins o
LEFT JOIN runs r ON r.id=o.source_run_id
LEFT JOIN system_runs s ON s.id=o.system_run_id
WHERE o.id = $1
`

type GetAsyncChatOriginRow struct {
	ID                   pgtype.UUID `json:"id"`
	AgentID              pgtype.UUID `json:"agent_id"`
	UserID               pgtype.UUID `json:"user_id"`
	SourceRunID          pgtype.UUID `json:"source_run_id"`
	SystemRunID          pgtype.UUID `json:"system_run_id"`
	ConversationID       pgtype.UUID `json:"conversation_id"`
	SystemConversationID pgtype.UUID `json:"system_conversation_id"`
}

func (q *Queries) GetAsyncChatOrigin(ctx context.Context, id pgtype.UUID) (GetAsyncChatOriginRow, error) {
	row := q.db.QueryRow(ctx, getAsyncChatOrigin, id)
	var i GetAsyncChatOriginRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.SourceRunID,
		&i.SystemRunID,
		&i.ConversationID,
		&i.SystemConversationID,
	)
	return i, err
}
