// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_runtime.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireConversationRunLease = `-- name: AcquireConversationRunLease :execrows
WITH acquired AS (
INSERT INTO conversation_run_leases (conversation_id, run_id, owner_token, lease_until, cancel_requested)
SELECT c.id, r.id, $1, now() + interval '30 seconds', false
FROM agent_conversations c JOIN runs r ON r.caller_conversation_id = c.id AND r.agent_id = c.agent_id
WHERE c.id = $2 AND r.id = $3 AND r.status = 'running'
ON CONFLICT (conversation_id) DO NOTHING
RETURNING run_id, owner_token
)
UPDATE runs SET runtime_owner_token = acquired.owner_token
FROM acquired WHERE runs.id = acquired.run_id
`

type AcquireConversationRunLeaseParams struct {
	OwnerToken     pgtype.UUID `json:"owner_token"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	RunID          pgtype.UUID `json:"run_id"`
}

func (q *Queries) AcquireConversationRunLease(ctx context.Context, arg AcquireConversationRunLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireConversationRunLease, arg.OwnerToken, arg.ConversationID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const appendRuntimeTelemetry = `-- name: AppendRuntimeTelemetry :execrows
UPDATE runs SET actions = actions || $1::jsonb,
    stdout_log = left(stdout_log || $2::text, 1048576)
WHERE id = $3 AND agent_id = $4 AND status = 'running'
`

type AppendRuntimeTelemetryParams struct {
	Actions []byte      `json:"actions"`
	Logs    string      `json:"logs"`
	RunID   pgtype.UUID `json:"run_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) AppendRuntimeTelemetry(ctx context.Context, arg AppendRuntimeTelemetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, appendRuntimeTelemetry,
		arg.Actions,
		arg.Logs,
		arg.RunID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeCapabilityRun = `-- name: CompleteCapabilityRun :execrows
UPDATE runs SET status = $1, error_message = $2,
    finished_at = now(), duration_ms = (EXTRACT(EPOCH FROM (now() - started_at)) * 1000)::integer
WHERE id = $3 AND status = 'running' AND runtime_owner_token IS NULL
`

type CompleteCapabilityRunParams struct {
	Status       string      `json:"status"`
	ErrorMessage string      `json:"error_message"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) CompleteCapabilityRun(ctx context.Context, arg CompleteCapabilityRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCapabilityRun, arg.Status, arg.ErrorMessage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeHostedRun = `-- name: CompleteHostedRun :execrows
UPDATE runs SET status = CASE WHEN status = 'cancelled' THEN status ELSE $1 END,
    error_message = CASE WHEN status = 'cancelled' THEN error_message ELSE $2 END,
    error_kind = $3, checkpoint = $4,
    finished_at = now(), duration_ms = (EXTRACT(EPOCH FROM (now() - started_at)) * 1000)::integer
WHERE id = $5 AND runtime_owner_token = $6 AND status IN ('running', 'cancelled')
`

type CompleteHostedRunParams struct {
	Status       string      `json:"status"`
	ErrorMessage string      `json:"error_message"`
	ErrorKind    string      `json:"error_kind"`
	Checkpoint   []byte      `json:"checkpoint"`
	RunID        pgtype.UUID `json:"run_id"`
	OwnerToken   pgtype.UUID `json:"owner_token"`
}

func (q *Queries) CompleteHostedRun(ctx context.Context, arg CompleteHostedRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeHostedRun,
		arg.Status,
		arg.ErrorMessage,
		arg.ErrorKind,
		arg.Checkpoint,
		arg.RunID,
		arg.OwnerToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRuntimeCheckpointInvalidation = `-- name: DeleteRuntimeCheckpointInvalidation :exec
DELETE FROM runtime_checkpoint_invalidations WHERE run_id = $1
`

func (q *Queries) DeleteRuntimeCheckpointInvalidation(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRuntimeCheckpointInvalidation, runID)
	return err
}

const getRuntimeManifest = `-- name: GetRuntimeManifest :one
SELECT m.manifest FROM agent_runtime_manifests m
JOIN agents a ON a.id = m.agent_id AND a.agent_token_version = m.token_version
WHERE m.agent_id = $1
`

func (q *Queries) GetRuntimeManifest(ctx context.Context, agentID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRuntimeManifest, agentID)
	var manifest []byte
	err := row.Scan(&manifest)
	return manifest, err
}

const isConversationRunOwned = `-- name: IsConversationRunOwned :one
SELECT EXISTS (SELECT 1 FROM runs WHERE caller_conversation_id = $1 AND runtime_owner_token IS NOT NULL)
`

func (q *Queries) IsConversationRunOwned(ctx context.Context, conversationID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationRunOwned, conversationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isRuntimeLeaseLive = `-- name: IsRuntimeLeaseLive :one
SELECT EXISTS (
    SELECT 1 FROM conversation_run_leases l JOIN runs r ON r.id = l.run_id
    WHERE l.run_id = $1 AND l.owner_token = $2
    AND l.lease_until > now() AND NOT l.cancel_requested AND r.status = 'running'
)
`

type IsRuntimeLeaseLiveParams struct {
	RunID      pgtype.UUID `json:"run_id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) IsRuntimeLeaseLive(ctx context.Context, arg IsRuntimeLeaseLiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRuntimeLeaseLive, arg.RunID, arg.OwnerToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listExpiredConversationRunLeases = `-- name: ListExpiredConversationRunLeases :many
SELECT l.conversation_id, l.run_id, l.owner_token, l.lease_until, l.cancel_requested FROM conversation_run_leases l
WHERE l.lease_until <= now() AND NOT EXISTS (SELECT 1 FROM agent_task_calls c WHERE c.id = l.run_id)
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListExpiredConversationRunLeases(ctx context.Context) ([]ConversationRunLease, error) {
	rows, err := q.db.Query(ctx, listExpiredConversationRunLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationRunLease{}
	for rows.Next() {
		var i ConversationRunLease
		if err := rows.Scan(
			&i.ConversationID,
			&i.RunID,
			&i.OwnerToken,
			&i.LeaseUntil,
			&i.CancelRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeCheckpointInvalidations = `-- name: ListRuntimeCheckpointInvalidations :many
SELECT run_id FROM runtime_checkpoint_invalidations FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListRuntimeCheckpointInvalidations(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRuntimeCheckpointInvalidations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var run_id pgtype.UUID
		if err := rows.Scan(&run_id); err != nil {
			return nil, err
		}
		items = append(items, run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversationRunLease = `-- name: LockConversationRunLease :one
SELECT l.conversation_id FROM conversation_run_leases l JOIN runs r ON r.id = l.run_id
WHERE l.run_id = $1 AND l.owner_token = $2
AND l.lease_until > now() AND NOT l.cancel_requested AND r.status = 'running'
FOR UPDATE OF l, r
`

type LockConversationRunLeaseParams struct {
	RunID      pgtype.UUID `json:"run_id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) LockConversationRunLease(ctx context.Context, arg LockConversationRunLeaseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockConversationRunLease, arg.RunID, arg.OwnerToken)
	var conversation_id pgtype.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const lockFinishingConversationRunLease = `-- name: LockFinishingConversationRunLease :one
SELECT l.cancel_requested, r.status FROM conversation_run_leases l JOIN runs r ON r.id = l.run_id
WHERE l.run_id = $1 AND l.owner_token = $2 AND l.lease_until > now()
AND r.status IN ('running', 'cancelled')
FOR UPDATE OF l, r
`

type LockFinishingConversationRunLeaseParams struct {
	RunID      pgtype.UUID `json:"run_id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

type LockFinishingConversationRunLeaseRow struct {
	CancelRequested bool   `json:"cancel_requested"`
	Status          string `json:"status"`
}

func (q *Queries) LockFinishingConversationRunLease(ctx context.Context, arg LockFinishingConversationRunLeaseParams) (LockFinishingConversationRunLeaseRow, error) {
	row := q.db.QueryRow(ctx, lockFinishingConversationRunLease, arg.RunID, arg.OwnerToken)
	var i LockFinishingConversationRunLeaseRow
	err := row.Scan(&i.CancelRequested, &i.Status)
	return i, err
}

const releaseConversationRunLease = `-- name: ReleaseConversationRunLease :execrows
DELETE FROM conversation_run_leases WHERE run_id = $1 AND owner_token = $2
`

type ReleaseConversationRunLeaseParams struct {
	RunID      pgtype.UUID `json:"run_id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) ReleaseConversationRunLease(ctx context.Context, arg ReleaseConversationRunLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseConversationRunLease, arg.RunID, arg.OwnerToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewConversationRunLease = `-- name: RenewConversationRunLease :execrows
UPDATE conversation_run_leases l SET lease_until = now() + interval '30 seconds'
FROM runs r
WHERE l.run_id = $1 AND l.owner_token = $2
AND l.lease_until > now() AND NOT l.cancel_requested
AND r.id = l.run_id AND r.status = 'running'
`

type RenewConversationRunLeaseParams struct {
	RunID      pgtype.UUID `json:"run_id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) RenewConversationRunLease(ctx context.Context, arg RenewConversationRunLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewConversationRunLease, arg.RunID, arg.OwnerToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestConversationRunCancellation = `-- name: RequestConversationRunCancellation :execrows
UPDATE conversation_run_leases SET cancel_requested = true
WHERE run_id = $1
`

func (q *Queries) RequestConversationRunCancellation(ctx context.Context, runID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requestConversationRunCancellation, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storeRuntimeManifest = `-- name: StoreRuntimeManifest :execrows
INSERT INTO agent_runtime_manifests (agent_id, token_version, manifest, synced_at)
SELECT id, agent_token_version, $1, now() FROM agents
WHERE id = $2 AND agent_token_version = $3
ON CONFLICT (agent_id) DO UPDATE SET
    token_version = EXCLUDED.token_version,
    manifest = EXCLUDED.manifest,
    synced_at = EXCLUDED.synced_at
`

type StoreRuntimeManifestParams struct {
	Manifest     []byte      `json:"manifest"`
	AgentID      pgtype.UUID `json:"agent_id"`
	TokenVersion int64       `json:"token_version"`
}

func (q *Queries) StoreRuntimeManifest(ctx context.Context, arg StoreRuntimeManifestParams) (int64, error) {
	result, err := q.db.Exec(ctx, storeRuntimeManifest, arg.Manifest, arg.AgentID, arg.TokenVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
