// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM agent_conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationBySource = `-- name: GetConversationBySource :one
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations
WHERE agent_id = $1 AND user_id = $2 AND source = $3
`

type GetConversationBySourceParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Source  string      `json:"source"`
}

// Non-creating lookup used by the bridge manager when it needs to read
// per-chat settings before any new conversation row would be created.
func (q *Queries) GetConversationBySource(ctx context.Context, arg GetConversationBySourceParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, getConversationBySource, arg.AgentID, arg.UserID, arg.Source)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateConversation = `-- name: GetOrCreateConversation :one
WITH ins AS (
    INSERT INTO agent_conversations (agent_id, user_id, source, title, bridge_id, external_id, metadata, settings)
    VALUES ($1, $2, $3::text, $4, $5, $6, '{}'::jsonb, '{}'::jsonb)
    ON CONFLICT (agent_id, user_id, source) DO UPDATE
        SET updated_at = now(),
            bridge_id = COALESCE(EXCLUDED.bridge_id, agent_conversations.bridge_id),
            external_id = COALESCE(EXCLUDED.external_id, agent_conversations.external_id)
    RETURNING id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at
)
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM ins
LIMIT 1
`

type GetOrCreateConversationParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Source     string      `json:"source"`
	Title      string      `json:"title"`
	BridgeID   pgtype.UUID `json:"bridge_id"`
	ExternalID pgtype.Text `json:"external_id"`
}

type GetOrCreateConversationRow struct {
	ID                         pgtype.UUID        `json:"id"`
	AgentID                    pgtype.UUID        `json:"agent_id"`
	BridgeID                   pgtype.UUID        `json:"bridge_id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	Source                     string             `json:"source"`
	ExternalID                 pgtype.Text        `json:"external_id"`
	Title                      string             `json:"title"`
	Metadata                   []byte             `json:"metadata"`
	Settings                   []byte             `json:"settings"`
	ContextCheckpointMessageID pgtype.UUID        `json:"context_checkpoint_message_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

// DM-only: one conversation per user per agent per source. Upserts on (agent_id, user_id, source).
func (q *Queries) GetOrCreateConversation(ctx context.Context, arg GetOrCreateConversationParams) (GetOrCreateConversationRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateConversation,
		arg.AgentID,
		arg.UserID,
		arg.Source,
		arg.Title,
		arg.BridgeID,
		arg.ExternalID,
	)
	var i GetOrCreateConversationRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByAgent = `-- name: ListConversationsByAgent :many
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations
WHERE agent_id = $1 AND user_id = $2
ORDER BY updated_at DESC
`

type ListConversationsByAgentParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

// Returns conversations for the given agent visible to the given user.
func (q *Queries) ListConversationsByAgent(ctx context.Context, arg ListConversationsByAgentParams) ([]AgentConversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByAgent, arg.AgentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversation{}
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.BridgeID,
			&i.UserID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Metadata,
			&i.Settings,
			&i.ContextCheckpointMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationSettings = `-- name: UpdateConversationSettings :exec
UPDATE agent_conversations
SET settings = settings || $1::jsonb,
    updated_at = now()
WHERE id = $2
`

type UpdateConversationSettingsParams struct {
	Patch []byte      `json:"patch"`
	ID    pgtype.UUID `json:"id"`
}

// Merges a JSONB patch into agent_conversations.settings. Used by the
// /echo slash command and any future per-chat preferences.
func (q *Queries) UpdateConversationSettings(ctx context.Context, arg UpdateConversationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateConversationSettings, arg.Patch, arg.ID)
	return err
}
