// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_invocations.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeExecutionInvocation = `-- name: CloseExecutionInvocation :exec
UPDATE execution_invocations SET closed_at = clock_timestamp()
WHERE token_hash = $1 AND closed_at IS NULL
`

func (q *Queries) CloseExecutionInvocation(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, closeExecutionInvocation, tokenHash)
	return err
}

const createExecutionInvocation = `-- name: CreateExecutionInvocation :execrows
INSERT INTO execution_invocations(token_hash, run_id, agent_id, runtime_generation, created_at, expires_at, owner_token)
SELECT $1, r.id, app.id, app.agent_token_version, clock_timestamp(), $2, $3
FROM runs r JOIN agents app ON app.id = r.agent_id
WHERE r.id = $4 AND app.id = $5 AND r.status = 'running'
AND app.status IN ('active', 'building') AND app.agent_token_version = $6
AND r.runtime_owner_token IS NOT DISTINCT FROM $3::uuid
AND ($3::uuid IS NULL OR EXISTS (SELECT 1 FROM conversation_run_leases l
 WHERE l.run_id = r.id AND l.owner_token = $3 AND l.lease_until > now() AND NOT l.cancel_requested))
`

type CreateExecutionInvocationParams struct {
	TokenHash         []byte             `json:"token_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	OwnerToken        pgtype.UUID        `json:"owner_token"`
	RunID             pgtype.UUID        `json:"run_id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	RuntimeGeneration int64              `json:"runtime_generation"`
}

func (q *Queries) CreateExecutionInvocation(ctx context.Context, arg CreateExecutionInvocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createExecutionInvocation,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.OwnerToken,
		arg.RunID,
		arg.AgentID,
		arg.RuntimeGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const executionCallbackJobLive = `-- name: ExecutionCallbackJobLive :one
SELECT EXISTS (
    SELECT 1 FROM agent_job_attempts a JOIN agent_jobs j ON j.id = a.job_id
    JOIN agents app ON app.id = j.agent_id JOIN runs r ON r.id = a.run_id
    WHERE a.run_id = $1 AND j.agent_id = $2 AND r.agent_id = j.agent_id
    AND j.id = $3 AND a.attempt_number = $4 AND a.lease_token = $5
    AND a.runtime_generation = $6 AND app.agent_token_version = a.runtime_generation
    AND app.status IN ('active', 'building') AND r.status = 'running'
    AND j.status = 'running' AND j.cancel_requested_at IS NULL
    AND a.status = 'running' AND a.lease_expires_at > clock_timestamp()
)
`

type ExecutionCallbackJobLiveParams struct {
	RunID             pgtype.UUID `json:"run_id"`
	AgentID           pgtype.UUID `json:"agent_id"`
	JobID             pgtype.UUID `json:"job_id"`
	AttemptNumber     int32       `json:"attempt_number"`
	LeaseToken        pgtype.UUID `json:"lease_token"`
	RuntimeGeneration int64       `json:"runtime_generation"`
}

func (q *Queries) ExecutionCallbackJobLive(ctx context.Context, arg ExecutionCallbackJobLiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, executionCallbackJobLive,
		arg.RunID,
		arg.AgentID,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseToken,
		arg.RuntimeGeneration,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const executionInvocationCompletionAllowed = `-- name: ExecutionInvocationCompletionAllowed :one
SELECT EXISTS (
    SELECT 1 FROM runs r JOIN agents app ON app.id = r.agent_id
    JOIN execution_origins origin ON origin.id = r.origin_id AND origin.agent_id = r.agent_id
    WHERE r.id = $1 AND app.id = $2
    AND app.agent_token_version = $3 AND app.status IN ('active', 'building')
    AND r.status = 'running' AND r.runtime_owner_token IS NULL AND r.execution_kind <> 'prompt'
    AND origin.actor <> 'unknown'
    AND (origin.actor <> 'app' OR r.execution_kind = 'job' OR origin.runtime_generation = $3)
    AND ($4::bytea IS NULL OR EXISTS (
        SELECT 1 FROM execution_invocations i
        WHERE i.token_hash = $4 AND i.run_id = r.id AND i.agent_id = app.id
        AND i.runtime_generation = $3
        AND i.revoked_at IS NULL AND i.expires_at > clock_timestamp()
    ))
    AND (
        (r.execution_kind <> 'job' AND r.trigger_type <> 'job' AND $4::bytea IS NOT NULL)
        OR EXISTS (
            SELECT 1 FROM agent_job_attempts a JOIN agent_jobs j ON j.id = a.job_id
            WHERE a.run_id = r.id AND j.agent_id = app.id
            AND j.id = $5 AND a.attempt_number = $6 AND a.lease_token = $7
            AND a.runtime_generation = $3
            AND j.status = 'running' AND j.cancel_requested_at IS NULL
            AND a.status = 'running' AND a.lease_expires_at > clock_timestamp()
        )
    )
)
`

type ExecutionInvocationCompletionAllowedParams struct {
	RunID             pgtype.UUID `json:"run_id"`
	AgentID           pgtype.UUID `json:"agent_id"`
	RuntimeGeneration int64       `json:"runtime_generation"`
	TokenHash         []byte      `json:"token_hash"`
	JobID             pgtype.UUID `json:"job_id"`
	AttemptNumber     int32       `json:"attempt_number"`
	LeaseToken        pgtype.UUID `json:"lease_token"`
}

// A closed delivery receipt permits only terminal telemetry until its expiry.
// Completion never restores the initiating credential's operational authority.
func (q *Queries) ExecutionInvocationCompletionAllowed(ctx context.Context, arg ExecutionInvocationCompletionAllowedParams) (bool, error) {
	row := q.db.QueryRow(ctx, executionInvocationCompletionAllowed,
		arg.RunID,
		arg.AgentID,
		arg.RuntimeGeneration,
		arg.TokenHash,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseToken,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const executionInvocationLive = `-- name: ExecutionInvocationLive :one
SELECT EXISTS (
    SELECT 1 FROM execution_invocations i JOIN runs r ON r.id = i.run_id JOIN agents app ON app.id = i.agent_id
    WHERE i.token_hash = $1 AND i.run_id = $2 AND i.agent_id = $3
    AND r.agent_id = i.agent_id AND r.status = 'running'
    AND i.owner_token IS NOT DISTINCT FROM r.runtime_owner_token
    AND i.runtime_generation = $4 AND app.agent_token_version = i.runtime_generation
    AND app.status IN ('active', 'building')
    AND i.closed_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > clock_timestamp()
)
`

type ExecutionInvocationLiveParams struct {
	TokenHash         []byte      `json:"token_hash"`
	RunID             pgtype.UUID `json:"run_id"`
	AgentID           pgtype.UUID `json:"agent_id"`
	RuntimeGeneration int64       `json:"runtime_generation"`
}

func (q *Queries) ExecutionInvocationLive(ctx context.Context, arg ExecutionInvocationLiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, executionInvocationLive,
		arg.TokenHash,
		arg.RunID,
		arg.AgentID,
		arg.RuntimeGeneration,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getExecutionInvocationOwner = `-- name: GetExecutionInvocationOwner :one
SELECT owner_token FROM execution_invocations WHERE token_hash = $1
`

func (q *Queries) GetExecutionInvocationOwner(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getExecutionInvocationOwner, tokenHash)
	var owner_token pgtype.UUID
	err := row.Scan(&owner_token)
	return owner_token, err
}

const revokeExecutionInvocations = `-- name: RevokeExecutionInvocations :exec
UPDATE execution_invocations SET revoked_at = clock_timestamp()
WHERE run_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeExecutionInvocations(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeExecutionInvocations, runID)
	return err
}
