// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelExecutionJob = `-- name: CancelExecutionJob :execrows
UPDATE agent_jobs j SET cancel_requested_at = now(),updated_at = now(),state_version = state_version + 1
WHERE status = 'running' AND cancel_requested_at IS NULL
AND EXISTS (SELECT 1 FROM agent_job_attempts a WHERE a.job_id = j.id AND a.run_id = $1 AND a.status IN ('leased','running'))
`

func (q *Queries) CancelExecutionJob(ctx context.Context, runID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelExecutionJob, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimExecutionResume = `-- name: ClaimExecutionResume :execrows
UPDATE runs SET status = 'success' WHERE id = $1 AND status = 'suspended'
`

func (q *Queries) ClaimExecutionResume(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimExecutionResume, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createExecutionOrigin = `-- name: CreateExecutionOrigin :one
INSERT INTO execution_origins(id,agent_id,ingress,actor,credential_profile,user_id,conversation_id,session_id,auth_epoch,
    credential_expires_at,authenticated_at,audience,client_id,scope,credential_agent_id,runtime_generation,bridge_id,platform_identity_id,sender_id,chat_id,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,
    $10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,now()) RETURNING id, agent_id, ingress, actor, credential_profile, user_id, conversation_id, session_id, auth_epoch, credential_expires_at, authenticated_at, audience, client_id, scope, credential_agent_id, runtime_generation, bridge_id, platform_identity_id, sender_id, chat_id, created_at
`

type CreateExecutionOriginParams struct {
	ID                  pgtype.UUID        `json:"id"`
	AgentID             pgtype.UUID        `json:"agent_id"`
	Ingress             string             `json:"ingress"`
	Actor               string             `json:"actor"`
	CredentialProfile   string             `json:"credential_profile"`
	UserID              pgtype.UUID        `json:"user_id"`
	ConversationID      pgtype.UUID        `json:"conversation_id"`
	SessionID           pgtype.UUID        `json:"session_id"`
	AuthEpoch           pgtype.Int8        `json:"auth_epoch"`
	CredentialExpiresAt pgtype.Timestamptz `json:"credential_expires_at"`
	AuthenticatedAt     pgtype.Timestamptz `json:"authenticated_at"`
	Audience            pgtype.Text        `json:"audience"`
	ClientID            pgtype.Text        `json:"client_id"`
	Scope               pgtype.Text        `json:"scope"`
	CredentialAgentID   pgtype.UUID        `json:"credential_agent_id"`
	RuntimeGeneration   pgtype.Int8        `json:"runtime_generation"`
	BridgeID            pgtype.UUID        `json:"bridge_id"`
	PlatformIdentityID  pgtype.UUID        `json:"platform_identity_id"`
	SenderID            pgtype.Text        `json:"sender_id"`
	ChatID              pgtype.Text        `json:"chat_id"`
}

func (q *Queries) CreateExecutionOrigin(ctx context.Context, arg CreateExecutionOriginParams) (ExecutionOrigin, error) {
	row := q.db.QueryRow(ctx, createExecutionOrigin,
		arg.ID,
		arg.AgentID,
		arg.Ingress,
		arg.Actor,
		arg.CredentialProfile,
		arg.UserID,
		arg.ConversationID,
		arg.SessionID,
		arg.AuthEpoch,
		arg.CredentialExpiresAt,
		arg.AuthenticatedAt,
		arg.Audience,
		arg.ClientID,
		arg.Scope,
		arg.CredentialAgentID,
		arg.RuntimeGeneration,
		arg.BridgeID,
		arg.PlatformIdentityID,
		arg.SenderID,
		arg.ChatID,
	)
	var i ExecutionOrigin
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Ingress,
		&i.Actor,
		&i.CredentialProfile,
		&i.UserID,
		&i.ConversationID,
		&i.SessionID,
		&i.AuthEpoch,
		&i.CredentialExpiresAt,
		&i.AuthenticatedAt,
		&i.Audience,
		&i.ClientID,
		&i.Scope,
		&i.CredentialAgentID,
		&i.RuntimeGeneration,
		&i.BridgeID,
		&i.PlatformIdentityID,
		&i.SenderID,
		&i.ChatID,
		&i.CreatedAt,
	)
	return i, err
}

const getDurableOriginUser = `-- name: GetDurableOriginUser :one
SELECT u.id, u.email, u.display_name, u.tenant_role, u.password_hash, u.oidc_sub, u.must_change_password, u.created_at, u.updated_at, u.auth_epoch FROM users u JOIN execution_origins o ON o.user_id = u.id
WHERE o.id = $1 AND u.auth_epoch = o.auth_epoch AND NOT u.must_change_password
AND (o.session_id IS NULL OR EXISTS (SELECT 1 FROM user_sessions s WHERE s.id = o.session_id AND s.user_id = u.id AND s.revoked_at IS NULL))
AND (o.credential_profile != 'oauth_mcp' OR EXISTS (
    SELECT 1 FROM oauth_grants g JOIN oauth_clients c ON c.client_id = g.client_id
    WHERE g.user_id = u.id AND g.client_id = o.client_id AND g.agent_id = o.agent_id
    AND g.revoked_at IS NULL AND g.expires_at > now()
    AND 'mcp' = ANY(regexp_split_to_array(trim(g.scope), '\s+'))
    AND 'mcp' = ANY(regexp_split_to_array(trim(o.scope), '\s+'))))
AND (o.credential_profile != 'bridge' OR EXISTS (
    SELECT 1 FROM bridges b JOIN platform_identities i ON i.id = o.platform_identity_id
    WHERE b.id = o.bridge_id AND b.status = 'active' AND b.type = 'telegram'
    AND b.agent_id = o.credential_agent_id AND b.agent_id = o.agent_id
    AND i.platform = b.type AND i.platform_user_id = o.sender_id AND i.user_id = u.id
    AND o.chat_id = o.sender_id))
`

func (q *Queries) GetDurableOriginUser(ctx context.Context, originID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getDurableOriginUser, originID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TenantRole,
		&i.PasswordHash,
		&i.OidcSub,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthEpoch,
	)
	return i, err
}

const getExecutionJobAttempt = `-- name: GetExecutionJobAttempt :one
SELECT a.job_id, a.attempt_number, a.status, a.runtime_generation, a.lease_owner, a.lease_token, a.lease_expires_at, a.run_id, a.error_kind, a.error_message, a.leased_at, a.started_at, a.completed_at, a.created_at, a.updated_at FROM agent_job_attempts a JOIN agent_jobs j ON j.id = a.job_id JOIN agents app ON app.id = j.agent_id
WHERE a.run_id = $1 AND a.status = 'running' AND a.lease_expires_at > now()
AND a.runtime_generation = app.agent_token_version AND j.cancel_requested_at IS NULL
`

func (q *Queries) GetExecutionJobAttempt(ctx context.Context, runID pgtype.UUID) (AgentJobAttempt, error) {
	row := q.db.QueryRow(ctx, getExecutionJobAttempt, runID)
	var i AgentJobAttempt
	err := row.Scan(
		&i.JobID,
		&i.AttemptNumber,
		&i.Status,
		&i.RuntimeGeneration,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RunID,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.LeasedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionOrigin = `-- name: GetExecutionOrigin :one
SELECT id, agent_id, ingress, actor, credential_profile, user_id, conversation_id, session_id, auth_epoch, credential_expires_at, authenticated_at, audience, client_id, scope, credential_agent_id, runtime_generation, bridge_id, platform_identity_id, sender_id, chat_id, created_at FROM execution_origins WHERE id = $1
`

func (q *Queries) GetExecutionOrigin(ctx context.Context, id pgtype.UUID) (ExecutionOrigin, error) {
	row := q.db.QueryRow(ctx, getExecutionOrigin, id)
	var i ExecutionOrigin
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Ingress,
		&i.Actor,
		&i.CredentialProfile,
		&i.UserID,
		&i.ConversationID,
		&i.SessionID,
		&i.AuthEpoch,
		&i.CredentialExpiresAt,
		&i.AuthenticatedAt,
		&i.Audience,
		&i.ClientID,
		&i.Scope,
		&i.CredentialAgentID,
		&i.RuntimeGeneration,
		&i.BridgeID,
		&i.PlatformIdentityID,
		&i.SenderID,
		&i.ChatID,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionRouteAccess = `-- name: GetExecutionRouteAccess :one
SELECT access FROM agent_routes WHERE agent_id = $1 AND method || ' ' || path = $2
`

type GetExecutionRouteAccessParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	RouteRef string      `json:"route_ref"`
}

func (q *Queries) GetExecutionRouteAccess(ctx context.Context, arg GetExecutionRouteAccessParams) (string, error) {
	row := q.db.QueryRow(ctx, getExecutionRouteAccess, arg.AgentID, arg.RouteRef)
	var access string
	err := row.Scan(&access)
	return access, err
}

const getRunOrigin = `-- name: GetRunOrigin :one
SELECT o.id, o.agent_id, o.ingress, o.actor, o.credential_profile, o.user_id, o.conversation_id, o.session_id, o.auth_epoch, o.credential_expires_at, o.authenticated_at, o.audience, o.client_id, o.scope, o.credential_agent_id, o.runtime_generation, o.bridge_id, o.platform_identity_id, o.sender_id, o.chat_id, o.created_at FROM execution_origins o JOIN runs r ON r.origin_id = o.id WHERE r.id = $1
`

func (q *Queries) GetRunOrigin(ctx context.Context, runID pgtype.UUID) (ExecutionOrigin, error) {
	row := q.db.QueryRow(ctx, getRunOrigin, runID)
	var i ExecutionOrigin
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Ingress,
		&i.Actor,
		&i.CredentialProfile,
		&i.UserID,
		&i.ConversationID,
		&i.SessionID,
		&i.AuthEpoch,
		&i.CredentialExpiresAt,
		&i.AuthenticatedAt,
		&i.Audience,
		&i.ClientID,
		&i.Scope,
		&i.CredentialAgentID,
		&i.RuntimeGeneration,
		&i.BridgeID,
		&i.PlatformIdentityID,
		&i.SenderID,
		&i.ChatID,
		&i.CreatedAt,
	)
	return i, err
}

const latestExecutionSuspension = `-- name: LatestExecutionSuspension :one
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, stdout_log, error_message, error_kind, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at, parent_run_id, llm_tokens_cached, caller_user_id, caller_conversation_id, caller_access, runtime_owner_token, origin_id, execution_kind, resume_run_id FROM runs WHERE agent_id = $1 AND caller_conversation_id = $2
AND execution_kind = 'prompt' AND status = 'suspended' ORDER BY started_at DESC LIMIT 1
`

type LatestExecutionSuspensionParams struct {
	AgentID        pgtype.UUID `json:"agent_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) LatestExecutionSuspension(ctx context.Context, arg LatestExecutionSuspensionParams) (Run, error) {
	row := q.db.QueryRow(ctx, latestExecutionSuspension, arg.AgentID, arg.ConversationID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerRef,
		&i.SourceRef,
		&i.InputPayload,
		&i.Actions,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmCostEstimate,
		&i.DurationMs,
		&i.StdoutLog,
		&i.ErrorMessage,
		&i.ErrorKind,
		&i.ExitCode,
		&i.PanicTrace,
		&i.Checkpoint,
		&i.Compacted,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ParentRunID,
		&i.LlmTokensCached,
		&i.CallerUserID,
		&i.CallerConversationID,
		&i.CallerAccess,
		&i.RuntimeOwnerToken,
		&i.OriginID,
		&i.ExecutionKind,
		&i.ResumeRunID,
	)
	return i, err
}

const lockExecutionJobAttempt = `-- name: LockExecutionJobAttempt :one
SELECT a.job_id, a.attempt_number, a.status, a.runtime_generation, a.lease_owner, a.lease_token, a.lease_expires_at, a.run_id, a.error_kind, a.error_message, a.leased_at, a.started_at, a.completed_at, a.created_at, a.updated_at FROM agent_job_attempts a JOIN agent_jobs j ON j.id = a.job_id
WHERE a.job_id = $1 AND a.attempt_number = $2 AND a.lease_token = $3
AND a.status = 'leased' AND a.lease_expires_at > now() AND j.cancel_requested_at IS NULL FOR UPDATE OF a
`

type LockExecutionJobAttemptParams struct {
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

func (q *Queries) LockExecutionJobAttempt(ctx context.Context, arg LockExecutionJobAttemptParams) (AgentJobAttempt, error) {
	row := q.db.QueryRow(ctx, lockExecutionJobAttempt, arg.JobID, arg.AttemptNumber, arg.LeaseToken)
	var i AgentJobAttempt
	err := row.Scan(
		&i.JobID,
		&i.AttemptNumber,
		&i.Status,
		&i.RuntimeGeneration,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RunID,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.LeasedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockExecutionResume = `-- name: LockExecutionResume :one
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, stdout_log, error_message, error_kind, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at, parent_run_id, llm_tokens_cached, caller_user_id, caller_conversation_id, caller_access, runtime_owner_token, origin_id, execution_kind, resume_run_id FROM runs WHERE id = $1 AND agent_id = $2 AND execution_kind = 'prompt'
AND caller_conversation_id = $3 AND status = 'suspended' FOR UPDATE
`

type LockExecutionResumeParams struct {
	ID             pgtype.UUID `json:"id"`
	AgentID        pgtype.UUID `json:"agent_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) LockExecutionResume(ctx context.Context, arg LockExecutionResumeParams) (Run, error) {
	row := q.db.QueryRow(ctx, lockExecutionResume, arg.ID, arg.AgentID, arg.ConversationID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerRef,
		&i.SourceRef,
		&i.InputPayload,
		&i.Actions,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmCostEstimate,
		&i.DurationMs,
		&i.StdoutLog,
		&i.ErrorMessage,
		&i.ErrorKind,
		&i.ExitCode,
		&i.PanicTrace,
		&i.Checkpoint,
		&i.Compacted,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ParentRunID,
		&i.LlmTokensCached,
		&i.CallerUserID,
		&i.CallerConversationID,
		&i.CallerAccess,
		&i.RuntimeOwnerToken,
		&i.OriginID,
		&i.ExecutionKind,
		&i.ResumeRunID,
	)
	return i, err
}
