// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_usage.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLLMUnitRate = `-- name: GetLLMUnitRate :one
SELECT rate FROM llm_unit_rates
WHERE provider_catalog_id = $1
  AND model = $2
  AND unit_kind = $3
`

type GetLLMUnitRateParams struct {
	ProviderCatalogID string `json:"provider_catalog_id"`
	Model             string `json:"model"`
	UnitKind          string `json:"unit_kind"`
}

// Operator-set per-unit price for a model the token catalog can't price.
// No row ⇒ caller records units with cost 0 (honest, not a fabricated
// price). pgx returns pgx.ErrNoRows which the caller treats as "no rate".
func (q *Queries) GetLLMUnitRate(ctx context.Context, arg GetLLMUnitRateParams) (float64, error) {
	row := q.db.QueryRow(ctx, getLLMUnitRate, arg.ProviderCatalogID, arg.Model, arg.UnitKind)
	var rate float64
	err := row.Scan(&rate)
	return rate, err
}

const insertLLMUsage = `-- name: InsertLLMUsage :exec
INSERT INTO llm_usage (
    agent_id, run_id, build_id, user_id, conversation_id,
    provider_catalog_id, model, capability, call_kind, slug,
    tokens_in, tokens_out, tokens_cached, tokens_reasoning,
    units, unit_kind,
    cost_input, cost_output, cost_total,
    finish_reason, errored, latency_ms
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16,
    $17, $18, $19,
    $20, $21, $22
)
`

type InsertLLMUsageParams struct {
	AgentID           pgtype.UUID `json:"agent_id"`
	RunID             pgtype.UUID `json:"run_id"`
	BuildID           pgtype.UUID `json:"build_id"`
	UserID            pgtype.UUID `json:"user_id"`
	ConversationID    pgtype.UUID `json:"conversation_id"`
	ProviderCatalogID string      `json:"provider_catalog_id"`
	Model             string      `json:"model"`
	Capability        string      `json:"capability"`
	CallKind          string      `json:"call_kind"`
	Slug              string      `json:"slug"`
	TokensIn          int64       `json:"tokens_in"`
	TokensOut         int64       `json:"tokens_out"`
	TokensCached      int64       `json:"tokens_cached"`
	TokensReasoning   int64       `json:"tokens_reasoning"`
	Units             float64     `json:"units"`
	UnitKind          string      `json:"unit_kind"`
	CostInput         float64     `json:"cost_input"`
	CostOutput        float64     `json:"cost_output"`
	CostTotal         float64     `json:"cost_total"`
	FinishReason      string      `json:"finish_reason"`
	Errored           bool        `json:"errored"`
	LatencyMs         int32       `json:"latency_ms"`
}

// One append-only row per proxied model HTTP round-trip. Cost is computed
// at capture (token rate from the sol/provider catalog, or llm_unit_rates
// for image/audio units) so this is a plain INSERT with no rate math here.
// run_id/user_id/conversation_id are nullable — an unattributed call still
// records its spend. id/created_at use column defaults.
func (q *Queries) InsertLLMUsage(ctx context.Context, arg InsertLLMUsageParams) error {
	_, err := q.db.Exec(ctx, insertLLMUsage,
		arg.AgentID,
		arg.RunID,
		arg.BuildID,
		arg.UserID,
		arg.ConversationID,
		arg.ProviderCatalogID,
		arg.Model,
		arg.Capability,
		arg.CallKind,
		arg.Slug,
		arg.TokensIn,
		arg.TokensOut,
		arg.TokensCached,
		arg.TokensReasoning,
		arg.Units,
		arg.UnitKind,
		arg.CostInput,
		arg.CostOutput,
		arg.CostTotal,
		arg.FinishReason,
		arg.Errored,
		arg.LatencyMs,
	)
	return err
}
