// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: managed_bot_sessions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManagedBotSession = `-- name: CreateManagedBotSession :one

INSERT INTO managed_bot_sessions (owner_id, agent_id, is_system, nonce, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, agent_id, is_system, nonce, expires_at, created_at
`

type CreateManagedBotSessionParams struct {
	OwnerID   pgtype.UUID        `json:"owner_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	IsSystem  bool               `json:"is_system"`
	Nonce     string             `json:"nonce"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// managed_bot_sessions: per-create-flow correlation rows tying an
// airlock "Create new Telegram bot" click to the eventual
// ManagedBotCreated callback the manager bot receives.
func (q *Queries) CreateManagedBotSession(ctx context.Context, arg CreateManagedBotSessionParams) (ManagedBotSession, error) {
	row := q.db.QueryRow(ctx, createManagedBotSession,
		arg.OwnerID,
		arg.AgentID,
		arg.IsSystem,
		arg.Nonce,
		arg.ExpiresAt,
	)
	var i ManagedBotSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AgentID,
		&i.IsSystem,
		&i.Nonce,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteManagedBotSession = `-- name: DeleteManagedBotSession :exec
DELETE FROM managed_bot_sessions WHERE id = $1
`

func (q *Queries) DeleteManagedBotSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteManagedBotSession, id)
	return err
}

const deleteManagedBotSessionByNonce = `-- name: DeleteManagedBotSessionByNonce :exec
DELETE FROM managed_bot_sessions WHERE nonce = $1
`

func (q *Queries) DeleteManagedBotSessionByNonce(ctx context.Context, nonce string) error {
	_, err := q.db.Exec(ctx, deleteManagedBotSessionByNonce, nonce)
	return err
}

const getLatestOpenManagedBotSessionByOwner = `-- name: GetLatestOpenManagedBotSessionByOwner :one
SELECT id, owner_id, agent_id, is_system, nonce, expires_at, created_at FROM managed_bot_sessions
WHERE owner_id = $1
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

// The owner's most recent non-expired session. Used by the manager-bot
// poller to correlate a ManagedBotUpdated callback to its airlock
// session (the Bot API 9.6 event carries only {user, bot} — no nonce
// echo — so we match by user.id → platform_identities → owner_id
// → most recent open session).
func (q *Queries) GetLatestOpenManagedBotSessionByOwner(ctx context.Context, ownerID pgtype.UUID) (ManagedBotSession, error) {
	row := q.db.QueryRow(ctx, getLatestOpenManagedBotSessionByOwner, ownerID)
	var i ManagedBotSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AgentID,
		&i.IsSystem,
		&i.Nonce,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getManagedBotSessionByNonce = `-- name: GetManagedBotSessionByNonce :one
SELECT id, owner_id, agent_id, is_system, nonce, expires_at, created_at FROM managed_bot_sessions WHERE nonce = $1
`

func (q *Queries) GetManagedBotSessionByNonce(ctx context.Context, nonce string) (ManagedBotSession, error) {
	row := q.db.QueryRow(ctx, getManagedBotSessionByNonce, nonce)
	var i ManagedBotSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AgentID,
		&i.IsSystem,
		&i.Nonce,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const sweepExpiredManagedBotSessions = `-- name: SweepExpiredManagedBotSessions :exec
DELETE FROM managed_bot_sessions WHERE expires_at < now()
`

// Janitor: drop rows past their 15-minute TTL. Called on manager-bot
// Reload and as part of periodic cleanup. The CHECK constraint
// guarantees agent_id is valid (FK CASCADE handles agent deletion)
// so we can't leak rows pointing at deleted agents.
func (q *Queries) SweepExpiredManagedBotSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepExpiredManagedBotSessions)
	return err
}
