// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_admission.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateMCPRequest = `-- name: ActivateMCPRequest :execrows
UPDATE mcp_active_requests SET run_id = $1
WHERE target_agent_id = $2 AND principal_identity = $3
  AND request_id = $4::jsonb AND owner_token = $5
  AND run_id IS NULL AND expires_at > now()
`

type ActivateMCPRequestParams struct {
	RunID             pgtype.UUID `json:"run_id"`
	TargetAgentID     pgtype.UUID `json:"target_agent_id"`
	PrincipalIdentity string      `json:"principal_identity"`
	RequestID         []byte      `json:"request_id"`
	OwnerToken        pgtype.UUID `json:"owner_token"`
}

func (q *Queries) ActivateMCPRequest(ctx context.Context, arg ActivateMCPRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateMCPRequest,
		arg.RunID,
		arg.TargetAgentID,
		arg.PrincipalIdentity,
		arg.RequestID,
		arg.OwnerToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockMCPRequest = `-- name: LockMCPRequest :one
SELECT run_id, owner_token FROM mcp_active_requests
WHERE target_agent_id = $1 AND principal_identity = $2
  AND request_id = $3::jsonb AND expires_at > now()
FOR UPDATE
`

type LockMCPRequestParams struct {
	TargetAgentID     pgtype.UUID `json:"target_agent_id"`
	PrincipalIdentity string      `json:"principal_identity"`
	RequestID         []byte      `json:"request_id"`
}

type LockMCPRequestRow struct {
	RunID      pgtype.UUID `json:"run_id"`
	OwnerToken pgtype.UUID `json:"owner_token"`
}

func (q *Queries) LockMCPRequest(ctx context.Context, arg LockMCPRequestParams) (LockMCPRequestRow, error) {
	row := q.db.QueryRow(ctx, lockMCPRequest, arg.TargetAgentID, arg.PrincipalIdentity, arg.RequestID)
	var i LockMCPRequestRow
	err := row.Scan(&i.RunID, &i.OwnerToken)
	return i, err
}

const releaseMCPRequest = `-- name: ReleaseMCPRequest :exec
DELETE FROM mcp_active_requests
WHERE target_agent_id = $1 AND principal_identity = $2
  AND request_id = $3::jsonb AND owner_token = $4
`

type ReleaseMCPRequestParams struct {
	TargetAgentID     pgtype.UUID `json:"target_agent_id"`
	PrincipalIdentity string      `json:"principal_identity"`
	RequestID         []byte      `json:"request_id"`
	OwnerToken        pgtype.UUID `json:"owner_token"`
}

func (q *Queries) ReleaseMCPRequest(ctx context.Context, arg ReleaseMCPRequestParams) error {
	_, err := q.db.Exec(ctx, releaseMCPRequest,
		arg.TargetAgentID,
		arg.PrincipalIdentity,
		arg.RequestID,
		arg.OwnerToken,
	)
	return err
}

const reserveMCPRequest = `-- name: ReserveMCPRequest :execrows
INSERT INTO mcp_active_requests (target_agent_id, principal_identity, request_id, owner_token, expires_at)
VALUES ($1, $2, $3::jsonb, $4, now() + interval '5 minutes')
ON CONFLICT (target_agent_id, principal_identity, request_id) DO UPDATE SET
    run_id = NULL, owner_token = EXCLUDED.owner_token,
    expires_at = EXCLUDED.expires_at, created_at = now()
WHERE mcp_active_requests.expires_at <= now()
`

type ReserveMCPRequestParams struct {
	TargetAgentID     pgtype.UUID `json:"target_agent_id"`
	PrincipalIdentity string      `json:"principal_identity"`
	RequestID         []byte      `json:"request_id"`
	OwnerToken        pgtype.UUID `json:"owner_token"`
}

func (q *Queries) ReserveMCPRequest(ctx context.Context, arg ReserveMCPRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveMCPRequest,
		arg.TargetAgentID,
		arg.PrincipalIdentity,
		arg.RequestID,
		arg.OwnerToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
