// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_active_requests.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredMCPActiveRequests = `-- name: CleanupExpiredMCPActiveRequests :execrows
DELETE FROM mcp_active_requests WHERE expires_at <= now()
`

func (q *Queries) CleanupExpiredMCPActiveRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredMCPActiveRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMCPActiveRequest = `-- name: GetMCPActiveRequest :one
SELECT run_id FROM mcp_active_requests
WHERE target_agent_id = $1
  AND principal_identity = $2
  AND request_id = $3::jsonb
  AND run_id = $4
  AND expires_at > now()
`

type GetMCPActiveRequestParams struct {
	TargetAgentID     pgtype.UUID `json:"target_agent_id"`
	PrincipalIdentity string      `json:"principal_identity"`
	RequestID         []byte      `json:"request_id"`
	RunID             pgtype.UUID `json:"run_id"`
}

// The owner observes durable cancellation even when another replica handled it.
func (q *Queries) GetMCPActiveRequest(ctx context.Context, arg GetMCPActiveRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMCPActiveRequest,
		arg.TargetAgentID,
		arg.PrincipalIdentity,
		arg.RequestID,
		arg.RunID,
	)
	var run_id pgtype.UUID
	err := row.Scan(&run_id)
	return run_id, err
}
