// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO agent_messages (conversation_id, role, content, parts, tokens_in, tokens_out, cost_estimate, run_id, source, ephemeral)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, 0), $8, COALESCE(NULLIF($9, ''), 'user'), $10)
RETURNING id, conversation_id, run_id, role, source, content, parts, file_keys, tokens_in, tokens_out, cost_estimate, ephemeral, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
	Parts          []byte      `json:"parts"`
	TokensIn       int32       `json:"tokens_in"`
	TokensOut      int32       `json:"tokens_out"`
	CostEstimate   interface{} `json:"cost_estimate"`
	RunID          pgtype.UUID `json:"run_id"`
	Source         interface{} `json:"source"`
	Ephemeral      bool        `json:"ephemeral"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (AgentMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Parts,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostEstimate,
		arg.RunID,
		arg.Source,
		arg.Ephemeral,
	)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RunID,
		&i.Role,
		&i.Source,
		&i.Content,
		&i.Parts,
		&i.FileKeys,
		&i.TokensIn,
		&i.TokensOut,
		&i.CostEstimate,
		&i.Ephemeral,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessagesByConversation = `-- name: DeleteMessagesByConversation :exec
DELETE FROM agent_messages
WHERE conversation_id = $1
`

func (q *Queries) DeleteMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessagesByConversation, conversationID)
	return err
}

const listAllMessagesByConversation = `-- name: ListAllMessagesByConversation :many
SELECT id, conversation_id, run_id, role, source, content, parts, file_keys, tokens_in, tokens_out, cost_estimate, ephemeral, created_at FROM agent_messages
WHERE conversation_id = $1
ORDER BY
  COALESCE(MIN(created_at) FILTER (WHERE run_id IS NOT NULL) OVER (PARTITION BY run_id), created_at) ASC,
  ephemeral ASC,
  created_at ASC
`

// UI loading — includes all messages.
func (q *Queries) ListAllMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listAllMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.FileKeys,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.Ephemeral,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBackward = `-- name: ListMessagesBackward :many
SELECT id, conversation_id, run_id, role, source, content, parts, file_keys, tokens_in, tokens_out, cost_estimate, ephemeral, created_at FROM (
    SELECT id, conversation_id, run_id, role, source, content, parts, file_keys, tokens_in, tokens_out, cost_estimate, ephemeral, created_at FROM agent_messages
    WHERE conversation_id = $1
      AND created_at < $2
    ORDER BY created_at DESC
    LIMIT $3
) t
ORDER BY created_at ASC
`

type ListMessagesBackwardParams struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Before         pgtype.Timestamptz `json:"before"`
	Lim            int32              `json:"lim"`
}

// Older page for infinite-scroll-up. Returns up to @lim messages strictly
// older than @before, back in chronological order for easy prepend.
func (q *Queries) ListMessagesBackward(ctx context.Context, arg ListMessagesBackwardParams) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesBackward, arg.ConversationID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.FileKeys,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.Ephemeral,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, run_id, role, source, content, parts, file_keys, tokens_in, tokens_out, cost_estimate, ephemeral, created_at FROM (
    SELECT id, conversation_id, run_id, role, source, content, parts, file_keys, tokens_in, tokens_out, cost_estimate, ephemeral, created_at FROM agent_messages
    WHERE conversation_id = $1
    ORDER BY created_at DESC
    LIMIT 101
) t
ORDER BY created_at ASC
`

// Initial UI page: the 100 most recent messages, returned in chronological
// order. The handler overfetches by one (LIMIT 101) so it can report
// has_older_messages without a second COUNT query; the extra row is trimmed
// before the response is built.
func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.FileKeys,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.Ephemeral,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByRun = `-- name: ListMessagesByRun :many
SELECT id, conversation_id, run_id, role, source, content, parts, file_keys, tokens_in, tokens_out, cost_estimate, ephemeral, created_at FROM agent_messages
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByRun(ctx context.Context, runID pgtype.UUID) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.FileKeys,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.Ephemeral,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesForward = `-- name: ListMessagesForward :many
SELECT id, conversation_id, run_id, role, source, content, parts, file_keys, tokens_in, tokens_out, cost_estimate, ephemeral, created_at FROM agent_messages
WHERE conversation_id = $1
  AND created_at > $2
ORDER BY created_at ASC
LIMIT $3
`

type ListMessagesForwardParams struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	After          pgtype.Timestamptz `json:"after"`
	Lim            int32              `json:"lim"`
}

// Newer page for scroll-down after eviction. Returns up to @lim messages
// strictly newer than @after, in chronological order.
func (q *Queries) ListMessagesForward(ctx context.Context, arg ListMessagesForwardParams) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesForward, arg.ConversationID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.FileKeys,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.Ephemeral,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionMessagesByConversation = `-- name: ListSessionMessagesByConversation :many
SELECT m.id, m.conversation_id, m.run_id, m.role, m.source, m.content, m.parts, m.file_keys, m.tokens_in, m.tokens_out, m.cost_estimate, m.ephemeral, m.created_at FROM agent_messages m
JOIN agent_conversations c ON c.id = m.conversation_id
WHERE m.conversation_id = $1
  AND NOT m.ephemeral
  AND m.source <> 'checkpoint'
  AND (
    c.context_checkpoint_message_id IS NULL
    OR m.created_at >= (
      SELECT created_at FROM agent_messages WHERE id = c.context_checkpoint_message_id
    )
  )
ORDER BY m.created_at ASC
`

// Agent context loading — excludes ephemeral messages (printToUser output) and
// messages before the active context checkpoint. When no checkpoint is set,
// returns all non-ephemeral messages. Checkpoint-marker rows (source='checkpoint')
// are UI-only metadata and are never sent to the LLM.
func (q *Queries) ListSessionMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listSessionMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.FileKeys,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.Ephemeral,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationCheckpoint = `-- name: SetConversationCheckpoint :exec
UPDATE agent_conversations
SET context_checkpoint_message_id = $1,
    updated_at = now()
WHERE id = $2
`

type SetConversationCheckpointParams struct {
	CheckpointMessageID pgtype.UUID `json:"checkpoint_message_id"`
	ConversationID      pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) SetConversationCheckpoint(ctx context.Context, arg SetConversationCheckpointParams) error {
	_, err := q.db.Exec(ctx, setConversationCheckpoint, arg.CheckpointMessageID, arg.ConversationID)
	return err
}

const sumPreCheckpointTokens = `-- name: SumPreCheckpointTokens :one
SELECT COALESCE(SUM(m.tokens_in + m.tokens_out), 0)::bigint AS total
FROM agent_messages m
JOIN agent_conversations c ON c.id = m.conversation_id
WHERE m.conversation_id = $1
  AND NOT m.ephemeral
  AND m.source <> 'checkpoint'
  AND (
    c.context_checkpoint_message_id IS NULL
    OR m.created_at >= (
      SELECT created_at FROM agent_messages WHERE id = c.context_checkpoint_message_id
    )
  )
`

// Sum of input+output tokens for messages before the current checkpoint
// (or all messages if no checkpoint is set). Used when a new checkpoint is
// being created to compute how many tokens are being freed.
func (q *Queries) SumPreCheckpointTokens(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumPreCheckpointTokens, conversationID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
