// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_states.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredOAuthStates = `-- name: CleanupExpiredOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at < now()
`

func (q *Queries) CleanupExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredOAuthStates)
	return err
}

const createOAuthState = `-- name: CreateOAuthState :exec
INSERT INTO oauth_states (state, agent_id, slug, code_verifier, redirect_uri, expires_at, source_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOAuthStateParams struct {
	State        string             `json:"state"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Slug         string             `json:"slug"`
	CodeVerifier string             `json:"code_verifier"`
	RedirectUri  string             `json:"redirect_uri"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	SourceType   string             `json:"source_type"`
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState,
		arg.State,
		arg.AgentID,
		arg.Slug,
		arg.CodeVerifier,
		arg.RedirectUri,
		arg.ExpiresAt,
		arg.SourceType,
	)
	return err
}

const deleteOAuthState = `-- name: DeleteOAuthState :exec
DELETE FROM oauth_states WHERE state = $1
`

func (q *Queries) DeleteOAuthState(ctx context.Context, state string) error {
	_, err := q.db.Exec(ctx, deleteOAuthState, state)
	return err
}

const getOAuthState = `-- name: GetOAuthState :one
SELECT state, agent_id, slug, source_type, code_verifier, redirect_uri, expires_at, created_at FROM oauth_states WHERE state = $1 AND expires_at > now()
`

func (q *Queries) GetOAuthState(ctx context.Context, state string) (OauthState, error) {
	row := q.db.QueryRow(ctx, getOAuthState, state)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.AgentID,
		&i.Slug,
		&i.SourceType,
		&i.CodeVerifier,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
