// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_identities.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlatformIdentity = `-- name: CreatePlatformIdentity :one
INSERT INTO platform_identities (user_id, platform, platform_user_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, platform, platform_user_id, created_at
`

type CreatePlatformIdentityParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Platform       string      `json:"platform"`
	PlatformUserID string      `json:"platform_user_id"`
}

func (q *Queries) CreatePlatformIdentity(ctx context.Context, arg CreatePlatformIdentityParams) (PlatformIdentity, error) {
	row := q.db.QueryRow(ctx, createPlatformIdentity, arg.UserID, arg.Platform, arg.PlatformUserID)
	var i PlatformIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlatformIdentity = `-- name: DeletePlatformIdentity :exec
DELETE FROM platform_identities WHERE id = $1 AND user_id = $2
`

type DeletePlatformIdentityParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePlatformIdentity(ctx context.Context, arg DeletePlatformIdentityParams) error {
	_, err := q.db.Exec(ctx, deletePlatformIdentity, arg.ID, arg.UserID)
	return err
}

const getPlatformIdentity = `-- name: GetPlatformIdentity :one
SELECT id, user_id, platform, platform_user_id, created_at FROM platform_identities
WHERE platform = $1 AND platform_user_id = $2
`

type GetPlatformIdentityParams struct {
	Platform       string `json:"platform"`
	PlatformUserID string `json:"platform_user_id"`
}

// Look up Airlock user by their platform identity
func (q *Queries) GetPlatformIdentity(ctx context.Context, arg GetPlatformIdentityParams) (PlatformIdentity, error) {
	row := q.db.QueryRow(ctx, getPlatformIdentity, arg.Platform, arg.PlatformUserID)
	var i PlatformIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listPlatformIdentitiesByUser = `-- name: ListPlatformIdentitiesByUser :many
SELECT id, user_id, platform, platform_user_id, created_at FROM platform_identities WHERE user_id = $1
`

func (q *Queries) ListPlatformIdentitiesByUser(ctx context.Context, userID pgtype.UUID) ([]PlatformIdentity, error) {
	rows, err := q.db.Query(ctx, listPlatformIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformIdentity{}
	for rows.Next() {
		var i PlatformIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PlatformUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlatformIdentity = `-- name: UpsertPlatformIdentity :one
INSERT INTO platform_identities (user_id, platform, platform_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (platform, platform_user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, platform, platform_user_id, created_at
`

type UpsertPlatformIdentityParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Platform       string      `json:"platform"`
	PlatformUserID string      `json:"platform_user_id"`
}

func (q *Queries) UpsertPlatformIdentity(ctx context.Context, arg UpsertPlatformIdentityParams) (PlatformIdentity, error) {
	row := q.db.QueryRow(ctx, upsertPlatformIdentity, arg.UserID, arg.Platform, arg.PlatformUserID)
	var i PlatformIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PlatformUserID,
		&i.CreatedAt,
	)
	return i, err
}
