// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (provider_id, display_name, api_key, base_url, is_enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider_id, display_name, is_enabled, base_url, api_key, created_at, updated_at
`

type CreateProviderParams struct {
	ProviderID  string `json:"provider_id"`
	DisplayName string `json:"display_name"`
	ApiKey      string `json:"api_key"`
	BaseUrl     string `json:"base_url"`
	IsEnabled   bool   `json:"is_enabled"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ProviderID,
		arg.DisplayName,
		arg.ApiKey,
		arg.BaseUrl,
		arg.IsEnabled,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.DisplayName,
		&i.IsEnabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, provider_id, display_name, is_enabled, base_url, api_key, created_at, updated_at FROM providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.DisplayName,
		&i.IsEnabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByProviderID = `-- name: GetProviderByProviderID :one
SELECT id, provider_id, display_name, is_enabled, base_url, api_key, created_at, updated_at FROM providers WHERE provider_id = $1
`

func (q *Queries) GetProviderByProviderID(ctx context.Context, providerID string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByProviderID, providerID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.DisplayName,
		&i.IsEnabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, provider_id, display_name, is_enabled, base_url, api_key, created_at, updated_at FROM providers ORDER BY provider_id
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.DisplayName,
			&i.IsEnabled,
			&i.BaseUrl,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET display_name = COALESCE(NULLIF($1::text, ''), display_name),
    api_key = CASE WHEN $2::boolean THEN $3 ELSE api_key END,
    base_url = COALESCE(NULLIF($4::text, ''), base_url),
    is_enabled = CASE WHEN $5::boolean THEN $6 ELSE is_enabled END,
    updated_at = now()
WHERE id = $7
RETURNING id, provider_id, display_name, is_enabled, base_url, api_key, created_at, updated_at
`

type UpdateProviderParams struct {
	DisplayName     string      `json:"display_name"`
	UpdateApiKey    bool        `json:"update_api_key"`
	ApiKey          string      `json:"api_key"`
	BaseUrl         string      `json:"base_url"`
	UpdateIsEnabled bool        `json:"update_is_enabled"`
	IsEnabled       bool        `json:"is_enabled"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.DisplayName,
		arg.UpdateApiKey,
		arg.ApiKey,
		arg.BaseUrl,
		arg.UpdateIsEnabled,
		arg.IsEnabled,
		arg.ID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.DisplayName,
		&i.IsEnabled,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
