// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: realtime_events.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRealtimeEventHead = `-- name: AdvanceRealtimeEventHead :one
UPDATE realtime_event_head
SET seq = seq + 1, byte_position = byte_position + octet_length($1::jsonb::text)
WHERE singleton RETURNING singleton, seq, byte_position, dropped_seq
`

func (q *Queries) AdvanceRealtimeEventHead(ctx context.Context, envelope []byte) (RealtimeEventHead, error) {
	row := q.db.QueryRow(ctx, advanceRealtimeEventHead, envelope)
	var i RealtimeEventHead
	err := row.Scan(
		&i.Singleton,
		&i.Seq,
		&i.BytePosition,
		&i.DroppedSeq,
	)
	return i, err
}

const insertRealtimeEvent = `-- name: InsertRealtimeEvent :exec
INSERT INTO realtime_events (seq, topic_id, envelope, byte_position, created_at)
VALUES ($1, $2, $3, $4, clock_timestamp())
`

type InsertRealtimeEventParams struct {
	Seq          int64       `json:"seq"`
	TopicID      pgtype.UUID `json:"topic_id"`
	Envelope     []byte      `json:"envelope"`
	BytePosition int64       `json:"byte_position"`
}

func (q *Queries) InsertRealtimeEvent(ctx context.Context, arg InsertRealtimeEventParams) error {
	_, err := q.db.Exec(ctx, insertRealtimeEvent,
		arg.Seq,
		arg.TopicID,
		arg.Envelope,
		arg.BytePosition,
	)
	return err
}

const lockRealtimeEventHead = `-- name: LockRealtimeEventHead :one
SELECT singleton, seq, byte_position, dropped_seq FROM realtime_event_head WHERE singleton FOR UPDATE
`

func (q *Queries) LockRealtimeEventHead(ctx context.Context) (RealtimeEventHead, error) {
	row := q.db.QueryRow(ctx, lockRealtimeEventHead)
	var i RealtimeEventHead
	err := row.Scan(
		&i.Singleton,
		&i.Seq,
		&i.BytePosition,
		&i.DroppedSeq,
	)
	return i, err
}

const notifyRealtimeEvents = `-- name: NotifyRealtimeEvents :exec
SELECT pg_notify('airlock_realtime_events', '')
`

func (q *Queries) NotifyRealtimeEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyRealtimeEvents)
	return err
}

const pruneRealtimeEvents = `-- name: PruneRealtimeEvents :exec
WITH removed AS (
    DELETE FROM realtime_events
    WHERE seq <= (SELECT seq - 4096 FROM realtime_event_head WHERE singleton)
       OR byte_position <= (SELECT byte_position - 16777216 FROM realtime_event_head WHERE singleton)
       OR created_at < clock_timestamp() - interval '10 minutes'
    RETURNING seq
)
UPDATE realtime_event_head
SET dropped_seq = GREATEST(dropped_seq, COALESCE((SELECT max(seq) FROM removed), 0))
WHERE singleton
`

func (q *Queries) PruneRealtimeEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneRealtimeEvents)
	return err
}

const readRealtimeEvents = `-- name: ReadRealtimeEvents :one
SELECT h.seq, h.dropped_seq, COALESCE((
    SELECT jsonb_agg(jsonb_build_object('seq', e.seq, 'topicId', e.topic_id, 'envelope', e.envelope) ORDER BY e.seq)
    FROM (
        SELECT seq, topic_id, envelope, byte_position, created_at FROM realtime_events
        WHERE seq > $1::bigint
          AND ($2::uuid IS NULL OR topic_id = $2::uuid)
        ORDER BY seq LIMIT $3::int
    ) e
), '[]'::jsonb)::jsonb AS events
FROM realtime_event_head h WHERE singleton
`

type ReadRealtimeEventsParams struct {
	Since      int64       `json:"since"`
	TopicID    pgtype.UUID `json:"topic_id"`
	EventLimit int32       `json:"event_limit"`
}

type ReadRealtimeEventsRow struct {
	Seq        int64  `json:"seq"`
	DroppedSeq int64  `json:"dropped_seq"`
	Events     []byte `json:"events"`
}

// Head, retention floor and envelopes come from one MVCC snapshot.
func (q *Queries) ReadRealtimeEvents(ctx context.Context, arg ReadRealtimeEventsParams) (ReadRealtimeEventsRow, error) {
	row := q.db.QueryRow(ctx, readRealtimeEvents, arg.Since, arg.TopicID, arg.EventLimit)
	var i ReadRealtimeEventsRow
	err := row.Scan(&i.Seq, &i.DroppedSeq, &i.Events)
	return i, err
}
