// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compactOldRuns = `-- name: CompactOldRuns :execrows
UPDATE runs SET
    input_payload = '{}'::jsonb,
    actions       = '[]'::jsonb,
    checkpoint    = NULL,
    logs          = '',
    stdout_log    = '',
    panic_trace   = '',
    compacted     = true
WHERE finished_at IS NOT NULL
    AND finished_at < $1
    AND compacted = false
`

// Nullify verbose fields on completed runs older than the cutoff.
// Aggregates (token counts, cost, duration, timestamps, status, error) are preserved.
func (q *Queries) CompactOldRuns(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, compactOldRuns, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRunsByAgent = `-- name: CountRunsByAgent :one
SELECT count(*) FROM runs WHERE agent_id = $1
`

func (q *Queries) CountRunsByAgent(ctx context.Context, agentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsByAgent, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (agent_id, bridge_id, status, input_payload, source_ref, trigger_type, trigger_ref)
VALUES ($1, $2, 'running', $3, $4, $5, $6)
RETURNING id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, logs, stdout_log, error_message, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at
`

type CreateRunParams struct {
	AgentID      pgtype.UUID `json:"agent_id"`
	BridgeID     pgtype.UUID `json:"bridge_id"`
	InputPayload []byte      `json:"input_payload"`
	SourceRef    string      `json:"source_ref"`
	TriggerType  string      `json:"trigger_type"`
	TriggerRef   string      `json:"trigger_ref"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.AgentID,
		arg.BridgeID,
		arg.InputPayload,
		arg.SourceRef,
		arg.TriggerType,
		arg.TriggerRef,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerRef,
		&i.SourceRef,
		&i.InputPayload,
		&i.Actions,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmCostEstimate,
		&i.DurationMs,
		&i.Logs,
		&i.StdoutLog,
		&i.ErrorMessage,
		&i.ExitCode,
		&i.PanicTrace,
		&i.Checkpoint,
		&i.Compacted,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestSuspendedRun = `-- name: GetLatestSuspendedRun :one
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, logs, stdout_log, error_message, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at FROM runs
WHERE agent_id = $1 AND status = 'suspended'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSuspendedRun(ctx context.Context, agentID pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getLatestSuspendedRun, agentID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerRef,
		&i.SourceRef,
		&i.InputPayload,
		&i.Actions,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmCostEstimate,
		&i.DurationMs,
		&i.Logs,
		&i.StdoutLog,
		&i.ErrorMessage,
		&i.ExitCode,
		&i.PanicTrace,
		&i.Checkpoint,
		&i.Compacted,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, logs, stdout_log, error_message, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at FROM runs WHERE id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerRef,
		&i.SourceRef,
		&i.InputPayload,
		&i.Actions,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmCostEstimate,
		&i.DurationMs,
		&i.Logs,
		&i.StdoutLog,
		&i.ErrorMessage,
		&i.ExitCode,
		&i.PanicTrace,
		&i.Checkpoint,
		&i.Compacted,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunCheckpoint = `-- name: GetRunCheckpoint :one
SELECT checkpoint FROM runs WHERE id = $1
`

func (q *Queries) GetRunCheckpoint(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRunCheckpoint, id)
	var checkpoint []byte
	err := row.Scan(&checkpoint)
	return checkpoint, err
}

const getSuspendedRunByID = `-- name: GetSuspendedRunByID :one
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, logs, stdout_log, error_message, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at FROM runs WHERE id = $1 AND status = 'suspended'
`

func (q *Queries) GetSuspendedRunByID(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getSuspendedRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerRef,
		&i.SourceRef,
		&i.InputPayload,
		&i.Actions,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmCostEstimate,
		&i.DurationMs,
		&i.Logs,
		&i.StdoutLog,
		&i.ErrorMessage,
		&i.ExitCode,
		&i.PanicTrace,
		&i.Checkpoint,
		&i.Compacted,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listRunningByAgent = `-- name: ListRunningByAgent :many
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, logs, stdout_log, error_message, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at FROM runs WHERE agent_id = $1 AND status = 'running'
`

func (q *Queries) ListRunningByAgent(ctx context.Context, agentID pgtype.UUID) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunningByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.BridgeID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerRef,
			&i.SourceRef,
			&i.InputPayload,
			&i.Actions,
			&i.LlmCalls,
			&i.LlmTokensIn,
			&i.LlmTokensOut,
			&i.LlmCostEstimate,
			&i.DurationMs,
			&i.Logs,
			&i.StdoutLog,
			&i.ErrorMessage,
			&i.ExitCode,
			&i.PanicTrace,
			&i.Checkpoint,
			&i.Compacted,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByAgent = `-- name: ListRunsByAgent :many
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, logs, stdout_log, error_message, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at FROM runs
WHERE agent_id = $1
    AND ($2::timestamptz IS NULL OR started_at < $2)
ORDER BY started_at DESC
LIMIT $3
`

type ListRunsByAgentParams struct {
	AgentID pgtype.UUID        `json:"agent_id"`
	Cursor  pgtype.Timestamptz `json:"cursor"`
	Lim     int32              `json:"lim"`
}

func (q *Queries) ListRunsByAgent(ctx context.Context, arg ListRunsByAgentParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByAgent, arg.AgentID, arg.Cursor, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.BridgeID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerRef,
			&i.SourceRef,
			&i.InputPayload,
			&i.Actions,
			&i.LlmCalls,
			&i.LlmTokensIn,
			&i.LlmTokensOut,
			&i.LlmCostEstimate,
			&i.DurationMs,
			&i.Logs,
			&i.StdoutLog,
			&i.ErrorMessage,
			&i.ExitCode,
			&i.PanicTrace,
			&i.Checkpoint,
			&i.Compacted,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStuckRuns = `-- name: ResetStuckRuns :exec
UPDATE runs SET
    status = 'failed',
    error_message = $1,
    finished_at = now(),
    duration_ms = EXTRACT(EPOCH FROM (now() - started_at))::integer * 1000
WHERE status = 'running'
`

func (q *Queries) ResetStuckRuns(ctx context.Context, errorMessage string) error {
	_, err := q.db.Exec(ctx, resetStuckRuns, errorMessage)
	return err
}

const resolveSuspendedRun = `-- name: ResolveSuspendedRun :exec
UPDATE runs SET status = 'success', finished_at = now()
WHERE id = $1 AND status = 'suspended'
`

func (q *Queries) ResolveSuspendedRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resolveSuspendedRun, id)
	return err
}

const updateRunCheckpoint = `-- name: UpdateRunCheckpoint :exec
UPDATE runs SET checkpoint = $1 WHERE id = $2
`

type UpdateRunCheckpointParams struct {
	Checkpoint []byte      `json:"checkpoint"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRunCheckpoint(ctx context.Context, arg UpdateRunCheckpointParams) error {
	_, err := q.db.Exec(ctx, updateRunCheckpoint, arg.Checkpoint, arg.ID)
	return err
}

const updateRunComplete = `-- name: UpdateRunComplete :exec
UPDATE runs SET
    status = $1,
    error_message = COALESCE($2, ''),
    actions = COALESCE($3, '[]'::jsonb),
    stdout_log = COALESCE($4, ''),
    panic_trace = COALESCE($5, ''),
    finished_at = now(),
    duration_ms = EXTRACT(EPOCH FROM (now() - started_at))::integer * 1000
WHERE id = $6
`

type UpdateRunCompleteParams struct {
	Status       string      `json:"status"`
	ErrorMessage string      `json:"error_message"`
	Actions      []byte      `json:"actions"`
	StdoutLog    string      `json:"stdout_log"`
	PanicTrace   string      `json:"panic_trace"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRunComplete(ctx context.Context, arg UpdateRunCompleteParams) error {
	_, err := q.db.Exec(ctx, updateRunComplete,
		arg.Status,
		arg.ErrorMessage,
		arg.Actions,
		arg.StdoutLog,
		arg.PanicTrace,
		arg.ID,
	)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE runs SET
    status = $1,
    finished_at = COALESCE(finished_at, now()),
    duration_ms = COALESCE(NULLIF(duration_ms, 0), EXTRACT(EPOCH FROM (now() - started_at))::integer * 1000)
WHERE id = $2 AND status = 'running'
`

type UpdateRunStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus, arg.Status, arg.ID)
	return err
}

const upsertRunComplete = `-- name: UpsertRunComplete :exec
INSERT INTO runs (id, agent_id, status, error_message, actions, stdout_log, panic_trace, input_payload, source_ref, trigger_type, trigger_ref, finished_at, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, '{}', '', 'prompt', '', now(), 0)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    error_message = EXCLUDED.error_message,
    actions = EXCLUDED.actions,
    stdout_log = EXCLUDED.stdout_log,
    panic_trace = EXCLUDED.panic_trace,
    finished_at = now(),
    duration_ms = EXTRACT(EPOCH FROM (now() - runs.started_at))::integer * 1000
`

type UpsertRunCompleteParams struct {
	ID           pgtype.UUID `json:"id"`
	AgentID      pgtype.UUID `json:"agent_id"`
	Status       string      `json:"status"`
	ErrorMessage string      `json:"error_message"`
	Actions      []byte      `json:"actions"`
	StdoutLog    string      `json:"stdout_log"`
	PanicTrace   string      `json:"panic_trace"`
}

func (q *Queries) UpsertRunComplete(ctx context.Context, arg UpsertRunCompleteParams) error {
	_, err := q.db.Exec(ctx, upsertRunComplete,
		arg.ID,
		arg.AgentID,
		arg.Status,
		arg.ErrorMessage,
		arg.Actions,
		arg.StdoutLog,
		arg.PanicTrace,
	)
	return err
}
