// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_origins.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSystemConversationRuns = `-- name: CancelSystemConversationRuns :execrows
UPDATE system_runs SET status='cancelled', finished_at=now()
WHERE conversation_id = $1 AND user_id = $2 AND status IN ('running','suspended')
`

type CancelSystemConversationRunsParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) CancelSystemConversationRuns(ctx context.Context, arg CancelSystemConversationRunsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSystemConversationRuns, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelSystemRun = `-- name: CancelSystemRun :execrows
UPDATE system_runs SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND conversation_id = $2 AND user_id = $3
AND status IN ('running', 'suspended')
`

type CancelSystemRunParams struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) CancelSystemRun(ctx context.Context, arg CancelSystemRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSystemRun, arg.ID, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSystemRunOrigin = `-- name: CreateSystemRunOrigin :exec
INSERT INTO system_run_origins (run_id, provenance) VALUES ($1, $2)
`

type CreateSystemRunOriginParams struct {
	RunID      pgtype.UUID `json:"run_id"`
	Provenance []byte      `json:"provenance"`
}

func (q *Queries) CreateSystemRunOrigin(ctx context.Context, arg CreateSystemRunOriginParams) error {
	_, err := q.db.Exec(ctx, createSystemRunOrigin, arg.RunID, arg.Provenance)
	return err
}

const getSystemRunOrigin = `-- name: GetSystemRunOrigin :one
SELECT provenance FROM system_run_origins WHERE run_id = $1
`

func (q *Queries) GetSystemRunOrigin(ctx context.Context, runID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSystemRunOrigin, runID)
	var provenance []byte
	err := row.Scan(&provenance)
	return provenance, err
}
