// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearActivationCode = `-- name: ClearActivationCode :exec
UPDATE system_settings
SET activation_code = NULL, updated_at = now()
WHERE id = true
`

func (q *Queries) ClearActivationCode(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearActivationCode)
	return err
}

const getSystemSettings = `-- name: GetSystemSettings :one
SELECT id, public_url, agent_domain, default_build_model, default_exec_model, default_stt_model, default_vision_model, default_tts_model, default_image_gen_model, default_embedding_model, default_search_model, activation_code, created_at, updated_at FROM system_settings WHERE id = true
`

func (q *Queries) GetSystemSettings(ctx context.Context) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSettings)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.AgentDomain,
		&i.DefaultBuildModel,
		&i.DefaultExecModel,
		&i.DefaultSttModel,
		&i.DefaultVisionModel,
		&i.DefaultTtsModel,
		&i.DefaultImageGenModel,
		&i.DefaultEmbeddingModel,
		&i.DefaultSearchModel,
		&i.ActivationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setActivationCode = `-- name: SetActivationCode :execrows
UPDATE system_settings
SET activation_code = $1, updated_at = now()
WHERE id = true AND activation_code IS NULL
`

// Sets the activation code only if one hasn't been set yet.
// Returns rows affected: 0 means another writer already set it.
func (q *Queries) SetActivationCode(ctx context.Context, activationCode pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, setActivationCode, activationCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSystemSettings = `-- name: UpdateSystemSettings :one
UPDATE system_settings
SET public_url = $1,
    agent_domain = $2,
    default_build_model = $3,
    default_exec_model = $4,
    default_stt_model = $5,
    default_vision_model = $6,
    default_tts_model = $7,
    default_image_gen_model = $8,
    default_embedding_model = $9,
    default_search_model = $10,
    updated_at = now()
WHERE id = true
RETURNING id, public_url, agent_domain, default_build_model, default_exec_model, default_stt_model, default_vision_model, default_tts_model, default_image_gen_model, default_embedding_model, default_search_model, activation_code, created_at, updated_at
`

type UpdateSystemSettingsParams struct {
	PublicUrl             string `json:"public_url"`
	AgentDomain           string `json:"agent_domain"`
	DefaultBuildModel     string `json:"default_build_model"`
	DefaultExecModel      string `json:"default_exec_model"`
	DefaultSttModel       string `json:"default_stt_model"`
	DefaultVisionModel    string `json:"default_vision_model"`
	DefaultTtsModel       string `json:"default_tts_model"`
	DefaultImageGenModel  string `json:"default_image_gen_model"`
	DefaultEmbeddingModel string `json:"default_embedding_model"`
	DefaultSearchModel    string `json:"default_search_model"`
}

func (q *Queries) UpdateSystemSettings(ctx context.Context, arg UpdateSystemSettingsParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, updateSystemSettings,
		arg.PublicUrl,
		arg.AgentDomain,
		arg.DefaultBuildModel,
		arg.DefaultExecModel,
		arg.DefaultSttModel,
		arg.DefaultVisionModel,
		arg.DefaultTtsModel,
		arg.DefaultImageGenModel,
		arg.DefaultEmbeddingModel,
		arg.DefaultSearchModel,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.PublicUrl,
		&i.AgentDomain,
		&i.DefaultBuildModel,
		&i.DefaultExecModel,
		&i.DefaultSttModel,
		&i.DefaultVisionModel,
		&i.DefaultTtsModel,
		&i.DefaultImageGenModel,
		&i.DefaultEmbeddingModel,
		&i.DefaultSearchModel,
		&i.ActivationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
