// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test_executors.sql

package dbq

import (
	"context"
)

const tryLockBuildTestExecutor = `-- name: TryLockBuildTestExecutor :one
SELECT pg_try_advisory_xact_lock(hashtextextended('test-executor:' || CAST($1 AS text), 0))::boolean
`

func (q *Queries) TryLockBuildTestExecutor(ctx context.Context, buildID string) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockBuildTestExecutor, buildID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
